packages:
  - type: github_release
    repo_owner: docker
    repo_name: hub-tool
    asset: hub-tool-{{.OS}}-{{.Arch}}.{{.Format}}
    format: tar.gz
    description: Docker Hub experimental CLI tool
    files:
      - name: hub-tool
        src: hub-tool/hub-tool
    overrides:
      - goos: windows
        format: zip
        files:
          - name: hub-tool
            src: hub-tool.exe
    supported_envs:
      - darwin
      - linux
      - amd64
