packages:
  - type: github_release
    repo_owner: helmfile
    repo_name: vals
    aliases:
      - name: variantdev/vals
    rosetta2: true
    asset: vals_{{trimV .Version}}_{{.OS}}_{{.Arch}}.tar.gz
    description: Helm-like configuration values loader with support for various sources
    checksum:
      type: github_release
      asset: vals_{{trimV .Version}}_checksums.txt
      file_format: regexp
      algorithm: sha256
      pattern:
        checksum: ^(\b[A-Fa-f0-9]{64}\b)
        file: "^\\b[A-Fa-f0-9]{64}\\b\\s+(\\S+)$"
