packages:
  - type: github_release
    repo_owner: kubernetes
    repo_name: kops
    asset: "kops-{{.OS}}-{{.Arch}}"
    description: Kubernetes Operations (kops) - Production Grade K8s Installation, Upgrades, and Management
