packages:
  - type: github_release
    repo_owner: kubernetes
    repo_name: kops
    description: Kubernetes Operations (kops) - Production Grade K8s Installation, Upgrades, and Management
    complete_windows_exe: false
    supported_if: not (GOOS == "windows" and GOARCH == "arm64")
    asset: "kops-{{.OS}}-{{.Arch}}"
