packages:
  - type: github_release
    repo_owner: kubernetes
    repo_name: kops
    description: Kubernetes Operations (kops) - Production Grade K8s Installation, Upgrades, and Management
    complete_windows_ext: false
    supported_envs:
      - darwin
      - linux
      - amd64
    asset: kops-{{.OS}}-{{.Arch}}
    checksum:
      type: github_release
      asset: protokube-linux-arm64.sha256
      file_format: regexp
      algorithm: sha256
      pattern:
        checksum: ^(.{64})
        file: "^.{64}\\s+(\\S+)$"
