---
# the configuration file of cmdx - task runner
# https://github.com/suzuki-shunsuke/cmdx
tasks:
  - name: install
    short: i
    description: install all packages
    usage: install all packages
    script: aqua -c aqua-all.yaml i --test
  - name: test
    short: t
    description: test
    usage: test
    script: aqua i --test
  - name: exec
    short: x
    description: exec with aqua-all.yaml
    usage: exec with aqua-all.yaml
    script: AQUA_CONFIG=aqua-all.yaml aqua exec -- {{._builtin.args_string}}
  - name: which
    short: w
    description: aqua which with aqua-all.yaml
    usage: aqua which with aqua-all.yaml
    script: "AQUA_CONFIG=aqua-all.yaml aqua which {{.package}}"
    args:
      - name: package
        required: true
  - name: generate
    short: g
    description: aqua generate with aqua-all.yaml
    usage: aqua generate with aqua-all.yaml
    script: aqua -c aqua-all.yaml g
  - name: release
    short: r
    description: release the new version
    usage: release the new version
    script: |
      git tag "{{.version}}"
      git push origin "{{.version}}"
    args:
      - name: version
        required: true
        validate:
          - regexp: "^v\\d+\\.\\d+.\\d+(-\\d+)?$"
  - name: registry
    short: gr
    description: Merge registry.yaml
    usage: Merge registry.yaml
    script: bash generate-registry.sh
  - name: scaffold
    short: s
    description: scaffold
    usage: scaffold
    script: bash scaffold.sh "{{.pkg}}"
    args:
      - name: pkg
        required: true
