packages:
  - type: github_release
    repo_owner: kubernetes
    repo_name: kompose
    description: Go from Docker Compose to Kubernetes
    format: raw
    version_constraint: 'semver(">= 1.26.0")'
    asset: kompose-{{.OS}}-{{.Arch}}
    version_overrides:
      - version_constraint: 'semver("< 1.26.0")'
        rosetta2: true
        asset: kompose-{{.OS}}-{{.Arch}}
