packages:
  - type: github_release
    repo_owner: kubernetes
    repo_name: kompose
    description: Go from Docker Compose to Kubernetes
    supported_envs:
      - darwin
      - linux
      - amd64
    format: raw
    version_constraint: semver(">= 1.26.0")
    asset: kompose-{{.OS}}-{{.Arch}}
    version_overrides:
      - version_constraint: "true"
        rosetta2: true
    checksum:
      type: github_release
      asset: SHA256_SUM
      file_format: regexp
      algorithm: sha256
      pattern:
        checksum: ^(\b[A-Fa-f0-9]{64}\b)
        file: "^\\b[A-Fa-f0-9]{64}\\b\\s+(\\S+)$"
