packages:
  - type: github_release
    repo_owner: grafana
    repo_name: tanka
    description: Flexible, reusable and concise configuration for Kubernetes
    rosetta2: true
    asset: "tk-{{.OS}}-{{.Arch}}"
    format: raw
    files:
      - name: tk
