packages:
  - type: github_release
    repo_owner: grafana
    repo_name: k6
    description: A modern load testing tool, using Go and JavaScript
    supported_if: not (GOOS == "windows" and GOARCH == "arm64")
    asset: "k6-{{.Version}}-{{.OS}}-{{.Arch}}.{{.Format}}"
    files:
      - name: k6
        src: "k6-{{.Version}}-{{.OS}}-{{.Arch}}/k6"
    replacements:
      darwin: macos
    format: zip
    overrides:
      - goos: linux
        format: tar.gz
