packages:
  - type: github_release
    repo_owner: helm
    repo_name: chart-testing
    description: CLI tool for linting and testing Helm charts
    asset: chart-testing_{{trimV .Version}}_{{.OS}}_{{.Arch}}.{{.Format}}
    format: tar.gz
    overrides:
      - goos: windows
        format: zip
    files:
      - name: ct
    checksum:
      type: github_release
      asset: checksums.txt.sig
      file_format: regexp
      algorithm: sha256
      pattern:
        checksum: ^(.{64})
        file: "^.{64}\\s+(\\S+)$"
