---
name: actionlint
env:
  AQUA_LOG_COLOR: always
on:
  push:
    branches: [main]
    paths:
      - .github/**
  pull_request:
    branches: [main]
    paths:
      - .github/**
permissions: {}
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - uses: aquaproj/aqua-installer@c0a879a13120ec4d55cadc8fc606ff296cd60b91 # v2.0.3-1
        with:
          aqua_version: v2.3.0-7
          policy_allow: "true"
      - run: actionlint -ignore "duplicate value"
